# Generated by Django 3.0.2 on 2020-01-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_category',
            field=models.CharField(blank=True, choices=[('ASIAN', 'ASIAN'), ('ITALIAN', 'ITALIAN'), ('MEXICAN', 'MEXICAN'), ('SWISS', 'SWISS')], max_length=30, null=True, verbose_name='restaurant_category'),
        ),
    ]
