# Generated by Django 3.0 on 2020-01-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_remove_restaurant_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_category',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('Asian', 'Asian'), ('Italian', 'Italian'), ('Mexican', 'Mexican'), ('Swiss', 'Swiss')], default='Asian', max_length=100, verbose_name='category'),
        ),
    ]
