# Generated by Django 3.0 on 2020-01-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20200122_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('Asian', 'Asian'), ('Italian', 'Italian'), ('Mexican', 'Mexican'), ('Swiss', 'Swiss')], default='Asian', max_length=150, verbose_name='category'),
        ),
    ]
