# Generated by Django 3.0 on 2020-01-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20200122_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='email',
            new_name='restaurant_email',
        ),
    ]
