version: '3'

services:
  backend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-10-november-2019/group-projects/aquarius
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: "tail -f /dev/null"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgresdb:/var/lib/postgresql/data



volumes:
  postgresdb:
