# Generated by Django 3.0 on 2020-01-22 14:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0007_auto_20200122_0930'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='review_content')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='restaurant_rating')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='date_modified')),
                ('comments', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='reviews_comments')),
                ('likes', models.ManyToManyField(blank=True, related_name='reviews_likes', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurants.Restaurant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-modified'],
                'unique_together': {('user', 'restaurant')},
            },
        ),
    ]
