# Generated by Django 3.0 on 2020-01-23 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_content', models.TextField(verbose_name='comments_content')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='date_modified')),
                ('comments_likes', models.ManyToManyField(blank=True, related_name='comments_likes', to=settings.AUTH_USER_MODEL)),
                ('restaurant_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rev_comments', to='reviews.Review')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
